// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://gxxfycdzmitblcdljark.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6Imd4eGZ5Y2R6bWl0YmxjZGxqYXJrIiwicm9sZSI6ImFub24iLCJpYXQiOjE3ODI2NTAzMzUsImV4cCI6MjA5ODIyNjMzNX0.0A8HDV6AulLfIeJyrRXeUCuwxvWkRf8xk19d_Vcv_Ec";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY, {
  auth: {
    storage: localStorage,
    persistSession: true,
    autoRefreshToken: true,
  }
});